terraform {
  required_providers {
    panos = {
      source  = "PaloAltoNetworks/panos"
      version = ">1.6"
    }
  }
}

resource "panos_administrative_tag" "tag" {
  for_each = var.services
  name    = each.value.id
  comment = "CTS autogenerated tag"
  color   = "color8"
}
